language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
before_install: cd src
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install tox
  - pip install -r requirements.txt
script:
  - tox
  - python3 setup.py sdist bdist_wheel
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_token coveralls
deploy:
  provider: pypi
  user: $pypi_user
  password: $pypi_password
  on:
    tags: true
