language: python
python:
  - 3.6
before_install: cd indian_stock_markets
install: pip install -r requirements.txt
script:
  - python3 -m unittest discover
  - python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: $pypi_user
  password: $pypi_password