CREATE TABLE IF NOT EXISTS FUTIDX
(
	SYMBOL TEXT NOT NULL,
	EXPIRY_DT TEXT NOT NULL,
	TIMESTAMP TEXT NOT NULL,
	OPEN REAL,
	HIGH REAL,
	LOW REAL,
	CLOSE REAL,
	SETTLE_PR REAL,
	CONTRACTS INTEGER,
	VAL_INLAKH REAL,
	OPEN_INT INTEGER,
	CHG_IN_OI REAL,
	PRIMARY KEY (SYMBOL, EXPIRY_DT, TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS FUTSTK
(
	SYMBOL TEXT NOT NULL,
	EXPIRY_DT TEXT NOT NULL,
	TIMESTAMP TEXT NOT NULL,
	OPEN REAL,
	HIGH REAL,
	LOW REAL,
	CLOSE REAL,
	SETTLE_PR REAL,
	CONTRACTS INTEGER,
	VAL_INLAKH REAL,
	OPEN_INT INTEGER,
	CHG_IN_OI REAL,
	PRIMARY KEY (SYMBOL, EXPIRY_DT, TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS OPTIDX
(
	SYMBOL TEXT NOT NULL,
	EXPIRY_DT TEXT NOT NULL,
	TIMESTAMP TEXT NOT NULL,
	STRIKE_PR REAL,
	OPTION_TYP TEXT,
	OPEN REAL,
	HIGH REAL,
	LOW REAL,
	CLOSE REAL,
	SETTLE_PR REAL,
	CONTRACTS INTEGER,
	VAL_INLAKH REAL,
	OPEN_INT INTEGER,
	CHG_IN_OI REAL,
	PRIMARY KEY (SYMBOL, EXPIRY_DT, TIMESTAMP, OPTION_TYP, STRIKE_PR)
);

CREATE TABLE IF NOT EXISTS OPTSTK
(
	SYMBOL TEXT NOT NULL,
	EXPIRY_DT TEXT NOT NULL,
	TIMESTAMP TEXT NOT NULL,
	STRIKE_PR REAL,
	OPTION_TYP TEXT,
	OPEN REAL,
	HIGH REAL,
	LOW REAL,
	CLOSE REAL,
	SETTLE_PR REAL,
	CONTRACTS INTEGER,
	VAL_INLAKH REAL,
	OPEN_INT INTEGER,
	CHG_IN_OI REAL,
	PRIMARY KEY (SYMBOL, EXPIRY_DT, TIMESTAMP, OPTION_TYP, STRIKE_PR)
);

CREATE TABLE IF NOT EXISTS SHORTSELLING
(
	SYMBOL TEXT NOT NULL,
	TRADE_DATE TEXT NOT NULL,
	QUANTITY INTEGER,
	PRIMARY KEY (SYMBOL, TRADE_DATE)
);